[package]
name = "cratesfyi"
version = "0.5.0"
authors = ["Onur Aslan <onuraslan@gmail.com>"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/mattlknight/cratesfyi"
build = "build.rs"

[dependencies]
log = "0.3"
rustc-serialize = "0.3"
regex = "0.2"
clap = "2"
crates-index-diff = "3"
git2 = "0.6"
time = "0.1"
reqwest = "0.5"
semver = "0.6"
slug = "=0.1.1"
env_logger = "0.4"
magic = "0.12"
r2d2 = "0.7"
r2d2_postgres = "0.12"
url = "1.4"
libc = "0.2"
badge = { version = "0", path = "src/web/badge" }
error-chain = "0.10"
comrak = { version = "0.2.10", default-features = false }
toml = "0.4"
html5ever = "0.22"

# iron dependencies
iron = "0.5"
router = "0.5"
handlebars-iron = "0.22"
params = "0.6"
staticfile = { version = "0.4", features = [ "cache" ] }

[dependencies.cargo]
version = "0.20.0"
git = "https://github.com/onur/cargo.git"
branch = "docs.rs"

[dependencies.postgres]
version = "0.14"
features = [ "with-time", "with-rustc-serialize" ]

[dev-dependencies]
tempdir = "0.3"

[build-dependencies]
time = "0.1"
git2 = "0.6"
sass-rs = "0.0.18"

[[bin]]
name = "cratesfyi"
test = false
doc = false
